fiPrice = float(input("Enter price of item 1 : "))
fiQuantity = float(input("Quantity of item 1 : "))
sePrice = float(input("Enter price of item 2 : "))
seQuantity = float(input("Quantity of item 2 : "))
thPrice = float(input("Enter price of item 3 : "))
thQuantity = float(input("Quantity of item 3 : "))
subtotal = (fiPrice*fiQuantity)+(sePrice*seQuantity)+(thPrice*thQuantity)
tax = round(subtotal * 0.055,3)
print("Subtotal :",subtotal,"\nTax :",tax,"\nTotal :",subtotal+tax)