noun = input("Enter a noun : ")
verb = input("Enter a verb : ")
adjective = input("Enter an adjective : ")
adverb = input("Enter an adverb : ")
print("Do you",adverb,"eat",verb,"ing",adjective,"",noun,"?")